sudo: false
language: node_js
node_js:
  # LTS
  - "8"
  - "10"
  - "node"
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm test
  - npm run lint
  - npm run docs:build
after_success:
  - npm run report-coverage
